=====================================================
DevCards API
=====================================================

@baseUrl = http://localhost:3000/api
@token =

=====================================================
Auth
=====================================================
Register

POST {{baseUrl}}/auth/register
Content-Type: application/json
{
"name": "Ivan",
"surname": "Atienza",
"email": "ivan@test.com",
"password": "123456",
"avatar_url": "https://es.pngtree.com/so/usuarios"
}

Login

POST {{baseUrl}}/auth/login
Content-Type: application/json
{
"email": "ivan@test.com",
"password": "123456"
}

=====================================================
Cards
=====================================================

Obtener cards del usuario

GET {{baseUrl}}/cards
Authorization: Bearer {{token}}

Obtener cards públicas

GET {{baseUrl}}/cards/public

Obtener card por ID

GET {{baseUrl}}/cards/1
Authorization: Bearer {{token}}

Crear card

POST {{baseUrl}}/cards
Authorization: Bearer {{token}}
Content-Type: application/json
{
"logo_url": "https://es.wikipedia.org/wiki/Archivo:Vue.js_Logo_2.svg",
"title": "Vue Docs",
"description": "Documentación Vue",
"documentation_url": "https://vuejs.org",
"is_public": 1,
"tags": ["vue","frontend"]
}

Actualizar card

PUT {{baseUrl}}/cards/1
Authorization: Bearer {{token}}
Content-Type: application/json
{
"logo_url": "https://vuejs.org/logo.png",
"title": “Documentación Vue",
"description": "Documentación Vue 3 Inglés",
"documentation_url": "https://vuejs.org",
"is_public": 1,
"tags": ["vue","frontend"]
}

Eliminar card

DELETE {{baseUrl}}/cards/1
Authorization: Bearer {{token}}

=====================================================
Tags
=====================================================

### Obtener tags

GET {{baseUrl}}/tags
Authorization: Bearer {{token}}

###

### Crear tag

POST {{baseUrl}}/tags
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "vue"
}

=====================================================
Profile
=====================================================

### Obtener perfil

GET {{baseUrl}}/users/profile
Authorization: Bearer {{token}}

###

### Actualizar perfil

PUT {{baseUrl}}/users/profile
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Ivan",
  "surname": "Atienza",
  "email": "ivan@test.com",
  "avatar_url": ""
}

=====================================================
Settings
=====================================================

Obtener settings

GET {{baseUrl}}/settings
Authorization: Bearer {{token}}

Actualizar settings

PUT {{baseUrl}}/settings
Authorization: Bearer {{token}}
Content-Type: application/json
{
"theme": "dark",
"language": "es"
}

=====================================================
Admin (users)
=====================================================

Obtener usuarios

GET {{baseUrl}}/users
Authorization: Bearer {{token}}

Actualizar usuario

PUT {{baseUrl}}/users/1
Authorization: Bearer {{token}}
Content-Type: application/json
{
"name": "Juan",
"surname": "Gonzalez",
"email": "admin@test.com",
"avatar": "https://es.pngtree.com/freepng/user-profile-avatar_13369991.html"
}

Eliminar usuario

DELETE {{baseUrl}}/users/1
Authorization: Bearer {{token}}